apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-http
  labels:
    app.kubernetes.io/name: simple-http
    app.kubernetes.io/managed-by: argocd
data:
  URL: https://www.google.com
  USER: steve
