apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
  labels:
    app.kubernetes.io/name: simple-http
    app.kubernetes.io/component: api-server
    app.kubernetes.io/managed-by: argocd
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-http
        app.kubernetes.io/component: api-server
        app.kubernetes.io/managed-by: argocd
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: simple-http
          image: httpd
          envFrom:
            - configMapRef:
                name: simple-http
            - secretRef:
                name: simple-http
          resources:
            limits:
              memory: 32M
              cpu: "1"
          startupProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: http
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "10"
          ports:
            - name: http
              containerPort: 80
