apiVersion: v1
kind: Service
metadata:
  name: simple-http
  labels:
    app.kubernetes.io/name: simple-http
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-http
  ports:
    - port: 80
      targetPort: 80
