apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    foo: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
        - name: simple-http
          image: httpd
          envFrom:
            - configMapRef:
                name: simple-http
            - secretRef:
                name: simple-http
          resources:
            limits:
              memory: 128M
              cpu: 1000m
          startupProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: http
          ports:
            - name: http
              containerPort: 80
